DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

CREATE TABLE IF NOT EXISTS roles(
role_id INTEGER NOT NULL PRIMARY KEY,
name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS users(
email VARCHAR(255) NOT NULL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_roles(
email VARCHAR(255) NOT NULL,
role_id INTEGER NOT NULL,
FOREIGN KEY(email) REFERENCES users(email) ON DELETE CASCADE,
FOREIGN KEY(role_id) REFERENCES roles(role_id) ON DELETE CASCADE
);

INSERT INTO roles VALUES(1, 'ROLE_USER');
INSERT INTO roles VALUES(2, 'ROLE_ADMIN');